### ISSUE TITLE
SCRIPT ERROR: @esx_documents/server.lua:146: attempt to index a nil value (local 'xPlayer') > TriggerServerCallback (@es_extended/server/functions.lua:160) > handler (@es_extended/server/common.lua:71) [

### ISSUE THREAD

**Issue by GermanGaming** [rocogamer/ESX_Documents#1]
Any idea where the error comes from?

SCRIPT ERROR: @esx_documents/server.lua:146: attempt to index a nil value (local 'xPlayer')
> TriggerServerCallback (@es_extended/server/functions.lua:160)
> handler (@es_extended/server/common.lua:71)
[

**Comment by rocogamer** [comment]
i will push a update to repair that error, wait a couple of minutes

**Comment by rocogamer** [comment]
I pushed a update to repair that
