### ISSUE TITLE
SCRIPT ERROR: @esx_documents/server.lua:65: attempt to index a nil value (local 'xPlayer') > TriggerServerCallback (@es_extended/server/functions.lua:160) > handler (@es_extended/server/common.lua:71)

### ISSUE THREAD

**Issue by GermanGaming** [rocogamer/ESX_Documents#2]
Thanks for the last fix. But now comes this error.

SCRIPT ERROR: @esx_documents/server.lua:65: attempt to index a nil value (local 'xPlayer')
> TriggerServerCallback (@es_extended/server/functions.lua:160)
> handler (@es_extended/server/common.lua:71)

**Comment by rocogamer** [comment]
Give me a couple of minutes please

**Comment by rocogamer** [comment]
Update pushed, sorry for the issues
